spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoescream
    hikari:
      username: root
      password: 1234
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: false
  sql.init.mode: always

jwt:
  secret-key: sideproject.shoescream-appliction-2024.secret_key
  token.expired-time-ms: 3600000
  refreshToken.expired-time-ms : 86400000

