spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
  datasource:
    url: ${DB_URL}
    hikari:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: junobee27@gmail.com
    password: wldmobkrapeqekky
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: false
  sql.init.mode: always

jwt:
  secret-key: sideproject.shoescream-appliction-2024.secret_key
  token.expired-time-ms: 3600000
  refreshToken.expired-time-ms: 86400000

